[package]
name = "retree"
version = "0.1.0"
edition = "2021"

[dependencies]
map-macro = "0.3.0"
log = "0.4.22"
simple_logger = "5.0.0"
dyn-clone = "1.0.19"
downcast = "0.11.0"
rand = "0.9.0"
rustyline = "15.0.0"
env_logger = "0.11.7"
