[package]
name = "oscpie_render"
version = "0.1.0"
edition = "2021"

[dependencies]
frame_counter = "0.1.2"
glam = "0.28.0"
image = "0.25.2"
miniquad = "0.4.5"

[dev-dependencies]
more-asserts = "0.3.1"
